### ISSUE TITLE
Why is cdk-import so slow?

### ISSUE THREAD

**Issue by eladb** [cdklabs/cdk-import#10]
From Tel-Aviv:

```
$ time npx cdk-import AWSQS::EKS::Cluster
0.88s user 0.19s system 7% cpu 14.626 total
```

14 seconds?

**Comment by hoegertn** [comment]
The listing of the types uses all the time. It seems the filtering is done client-side or at least not efficient. There are around 10 paginated list calls and one has the result in it. So this takes 5 seconds on my env with a total runtime of 5-6 seconds.

We could short-circuit this by also allowing to specify the ARN of the type. For mass generation, where the time is important, you could do one list call outside of the tool and then call it with all the arns.

I was able to generate within 800ms when providing the ARN.

**Comment by eladb** [comment]
> We could short-circuit this by also allowing to specify the ARN of the type. For mass generation, where the time is important, you could do one list call outside of the tool and then call it with all the arns.

Yes, I think that if an ARN is provided, the lookup should be skipped. This will definitely address the mass generation use case. That's the minimum I guess.
