### ISSUE TITLE
Adding sub commands for different import paths

### ISSUE THREAD

**Issue by arcrank** [cdklabs/cdk-import#203]
In near future, cdk-import will be able to import CDK constructs from more than just Cfn Registry.  
In light of that - would like to just confirm how the cli can be extended before making a PR.

Given CDK team input on using subcommands I thought it might be appropriate to add [minimist-subcommand](https://www.npmjs.com/package/minimist-subcommand) which would then allow us to do something like 

```
cdk-import sc -l python
```

We would just introduce this with new subcommand definition, we can add a subcommand definition for current path using something like `cfn`, but also set that as the default path, so the current usage would not be affected.
```
//same functionality
cdk-import -l python RESOURCE
cdk-import cfn -l python RESOURCE
```

Just wanted to see if there are any thoughts or majors issues with this approach.

**Comment by skinny85** [comment]
I like this approach, no concerns from me 🙂.

@corymhall do you want to opine here?

**Comment by corymhall** [comment]
Sounds good to me.
