### ISSUE TITLE
feat: Support oneOf

### ISSUE THREAD

**Issue by tenjaa** [cdklabs/cdk-import#293]
When having a `oneOf` property, it just generates `any` as typing.

It would be cool to have the type properly set like
```typescript
export interface CfnResourceProps {
  readonly myProperty?: CfnTypeA | CfnTypeB | CfnTypeC;

}
```

**Comment by tenjaa** [comment]
@mrgrain Sorry to bother you..
As you merged my other PR, do you have a hint on where to start to support this usecase?

**Comment by mrgrain** [comment]
Unfortunately I'm not very familiar with this package, just enough to review a simple PR. 😅

**Comment by tenjaa** [comment]
I did some digging today.
It looks like json2jsii does not support this.
Having a look at [this testcase](https://github.com/cdklabs/json2jsii/blob/374c193a7e562b39f52de930fe12d519be36a80e/test/__snapshots__/type-generator.test.ts.snap#L1115) you can see that it also just generates `any` instead of `string | number`.
I leave this open because I still think it would be an awesome feature but `any` it is.
