### ISSUE TITLE
New versions not getting published

### ISSUE THREAD

**Issue by tenjaa** [cdklabs/cdk-import#923]
Hi,
since some time new versions do not get published anymore.
The last published workflow: https://github.com/cdklabs/cdk-import/actions/runs/7950789940
The first not-published workflow: https://github.com/cdklabs/cdk-import/actions/runs/7960957810

**Comment by colifran** [comment]
Hi @tenjaa. Thank you for raising this issue. This has been fixed via this PR - https://github.com/cdklabs/cdk-import/pull/933
